#' Transform MC-100 Data Files
#'
#' This function processes raw data files generated by the MC-100 Chlorophyll Concentration Meter. It performs
#' preprocessing, merging with index data, and applies transformations to prepare the data for analysis.
#'
#' @param data A list containing raw data frames from the MC-100 device and associated index files.
#' @param split_code Logical. If `TRUE`, the function will split measurement codes into separate columns based on a configuration file.
#' @param env An environment object for logging warnings or errors during the processing.
#' @param folder_path description
#'
#' @return A list of transformed data frames, each representing the merged and transformed data.
#'
#' @details The function performs the following steps:
#' \itemize{
#'   \item **Preprocessing**: Standardizes the structure of data frames and adds necessary identifiers.
#'   \item **Merging**: Combines each raw data frame with its corresponding index data.
#'   \item **Transformations**: Selects columns, renames them, adds date columns, and converts data types.
#'   Optionally, it splits the `Code` column into multiple columns (e.g., `Landuse`, `Position`, `InterRow`).
#' }
#'
#' @noRd
map_MC100 <- function(data, split_code, env, variable, folder_path) {
  # ---- initial setup
  preprocessed_data <- preprocess_all_data_frames(data)
  csv_elements <- preprocessed_data$data_files_processed
  index_elements <- preprocessed_data$index_files_processed
  config_path <- file.path(dirname(folder_path), "config.txt")

  # ---- main part
  merged_data_frames <- merge_data_and_index_frames(csv_elements, index_elements)
  transformed_data_frames <- apply_transformations(merged_data_frames, variable)

  if (split_code) {
    if (file.exists(config_path)) {
      config <- read_simple_config(config_path)
      transformed_data_frames <- lapply(transformed_data_frames, function(df) {
        split_code_column(df, config, env) # Apply splitCodeColumn to get Landuse, Position, and InterRow columns!
      })
    } else {
      warning(
        "Input configuration file not found at: ", config_path,
        ". If you want to utilize the functionality of `split_code`, ensure your configuration file is placed at the correct path and follows the guidelines specified in the README."
      )
    }
  }

  return(transformed_data_frames)
}
