# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        r-version: ['4.3.3']

    steps:
      - uses: actions/checkout@v4

      # Setup R version
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@f57f1301a053485946083d7a45022b278929a78a
        with:
          r-version: ${{ matrix.r-version }}

      - name: Install pandoc
        run: |
          Invoke-WebRequest -Uri "https://github.com/jgm/pandoc/releases/download/2.19.2/pandoc-2.19.2-windows-x86_64.msi" -OutFile "pandoc.msi"
          Start-Process msiexec.exe -ArgumentList '/i', 'pandoc.msi', '/quiet', '/norestart' -NoNewWindow -Wait

       # Add Pandoc to PATH
      - name: Add Pandoc to PATH
        run: |
          $env:Path += ";C:\Program Files\Pandoc"
          Write-Host "Pandoc Path: $env:Path"

      # Check Pandoc installation
      - name: Check Pandoc installation
        run: |
          pandoc --version

      # Install Rtools for Windows
      - name: Install Rtools
        if: runner.os == 'Windows'
        run: |
          choco install rtools --no-progress
          
      # Install dependencies from DESCRIPTION file
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck", "devtools", "testthat", "rmarkdown"))
          remotes::install_cran("devtools", upgrade = "always")
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      # Install the VegetationAnalysisToolkit package from GitHub
      - name: Install VegetationAnalysisToolkit
        run: |
          remotes::install_github("anonymus06/VegetationAnalysisToolkit", auth_token = Sys.getenv("GH_PAT"))
        shell: Rscript {0}
        env:
          GH_PAT: ${{ secrets.GH_PAT }}

      - name: Load package
        run: |
          Rscript -e "library(VegetationAnalysisToolkit)"

      # Run tests with testthat
      # - name: Run tests
      # run: |
      #   devtools::test()
      # shell: Rscript {0}

      # Run devtools::check()
      - name: Check package
        run: |
          devtools::check(args = c('--no-manual', '--no-vignettes'))
        shell: Rscript {0}

      # Check package with rcmdcheck
      - name: Check with rcmdcheck
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}

      # Build package
      - name: Build package
        run: |
          devtools::build()
        shell: Rscript {0}
